spring:
  data:
    elasticsearch:
      repositories:
        enabled: true                #开启 Elasticsearch 仓库(默认值:true)
      cluster-nodes: 127.0.0.1:9300  #默认 9300 是 Java 客户端的端口。9200 是支持 Restful HTTP 的接口
      properties:
        transport:
          tcp:
            connect_timeout: 120s #连接超时的时间