spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/saas-export?characterEncoding=utf-8
    username: root
    password: "0820"
server:
  port: 9000
